<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page import="java.util.*, java.sql.*" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="mytag" tagdir="/WEB-INF/tags" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="${path }/resources/css/main.css" />
<title>Insert title here</title>
<style type="text/css">
.flip-vertical-right {
	-webkit-animation: flip-vertical-right 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
	        animation: flip-vertical-right 0.4s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-10-14 17:44:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-vertical-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
  }
}
@keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(180deg);
            transform: rotateY(180deg);
  }
}
</style>
</head>
<body class="flip-vertical-right subpage">
<mytag:navbar></mytag:navbar>
	<!-- One -->
	<section id="One" class="wrapper style3">
		<div class="inner">
			<header class="align-center">
				<p>Sed amet nulla</p>
				<h2>MASTER MENU(미구현)</h2>
			</header>
		</div>
	</section>
	
	<!-- Main -->
	<div id="main" class="container">
		<hr />
		<!-- Form -->
		<h3>MASTER MENU</h3>

		<form method="post" action="${path}/member/login">
			<div class="row uniform">
				<div class="6u 12u$(xsmall)">
					<input type="text" name="id" id="id" value="" placeholder="ID" />
				</div>
				<div class="6u$ 12u$(xsmall)">
					<input type="password" name="password" id="password" value="" placeholder="Password" />
				</div>
				<!-- break -->
				<div class="12u$">
					<ul class="actions">
						<li><input type="submit" value="Sign In" /></li>
					</ul>
				</div>
			</div>
		</form>

		<hr />

	</div>
	</div>
	</div>

	<!-- Footer -->
	<footer id="footer">
		<div class="container">
			<ul class="icons">
				<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
				<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
			</ul>
		</div>
		<div class="copyright">
			&copy; Untitled. All rights reserved.
		</div>
	</footer>

	<!-- Scripts -->
	<script src="${path }/resources/js/jquery.min.js"></script>
	<script src="${path }/resources/js/jquery.scrollex.min.js"></script>
	<script src="${path }/resources/js/skel.min.js"></script>
	<script src="${path }/resources/js/util.js"></script>
	<script src="${path }/resources/js/main.js"></script>
	<c:if test="${empty master }">
	<script type="text/javascript">
		alert("불허된 접근입니다.");
		location.href="${path }/index.jsp";
	</script>
	</c:if>
	<c:if test="${not empty master }">
		<% request.getSession().removeAttribute("master"); %>
	</c:if>

</body>
</html>