-- TABLE Declaration
create table MT_MEMBER_TB(
    M_ID VARCHAR2(20)
    , PW VARCHAR2(64)
    , M_NM VARCHAR2(16)
    , RANK_NM VARCHAR2(10)
    , DEL_FL CHAR(1)
);

create table DT_DEPARTMENT_TB (
    DEPT_CD VARCHAR2(20)
    , DEPT_NM VARCHAR2(40)
    , LFT NUMBER(4)
    , RGT NUMBER(4)
);

create table AMT_AUTH_MAP_TB (
    M_ID VARCHAR2(20)
    , DEPT_CD VARCHAR2(20)
);

create table RLT_REPORT_LOG_TB (
    R_IDX NUMBER(8)
    , OPT_CD NUMBER(4)
    , LOG_TIME TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE RT_REPORT_TB (
    R_IDX NUMBER(8)
    , WEEK VARCHAR2(7)
    , M_ID VARCHAR2(20)
    , MOD_ID VARCHAR2(20)
    , DEPT_CD NUMBER(4)
    , TITLE VARCHAR2(200)
    , REGDATE TIMESTAMP
    , MODDATE TIMESTAMP
    , DEL_FL CHAR(1)
);

CREATE TABLE WDT_WEEK_DATA_TB (
    WEEK VARCHAR2(7)
    , WEEK_START VARCHAR2(8)
    , WEEK_END VARCHAR2(8)
);

CREATE TABLE RDT_REPORT_DETAIL_TB (
    D_IDX NUMBER(8)
    , R_IDX NUMBER(8)
    , OPT_CD NUMBER(4)
    , CONTENT VARCHAR2(1600)
    , D_ORD NUMBER(2)
);

CREATE TABLE TMT_TABLE_MAP_TB (
    D_IDX NUMBER(8)
    , TAG_ID NUMBER(8)
);

CREATE TABLE TT_TAG_TB (
    TAG_ID NUMBER(8)
    , TAG_NM VARCHAR2(50)
);
-- TABLE Declaration End

-- SEQUENCE Declaration 
CREATE SEQUENCE RT_SEQ;
CREATE SEQUENCE RDT_SEQ;
CREATE SEQUENCE TT_SEQ;
-- SEQUENCE Declaration End